const clean=(s='')=>String(s??'').replace(/\s+/g,' ').trim();
const norm=(s='')=>clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={target:null,records:{}},job=null,runner=null,bridgeReady=false;
let targetEditing=false,targetDraft=sessionStorage.getItem('mlRadarTargetDraft')||'';
const $=s=>document.querySelector(s), pending=new Map();
const direct=()=>!!(globalThis.chrome?.runtime?.id && location.protocol==='chrome-extension:');
window.addEventListener('message',ev=>{const d=ev.data;if(!d)return;if(d.source==='ML_RADAR_V14_SITE_READY'){bridgeReady=true;return;}if(d.source==='ML_RADAR_V14_SITE_RES'&&pending.has(d.id)){const p=pending.get(d.id);pending.delete(d.id);d.error?p.reject(new Error(d.error)):p.resolve(d.response);return;}if(d.source==='ML_RADAR_V14_PUSH'&&d.payload)handlePush(d.payload);});
function msg(payload){if(direct())return new Promise((resolve,reject)=>chrome.runtime.sendMessage(payload,r=>{if(chrome.runtime.lastError)reject(chrome.runtime.lastError);else resolve(r)}));return new Promise((resolve,reject)=>{const id='r'+Date.now()+Math.random().toString(36).slice(2);pending.set(id,{resolve,reject});window.postMessage({source:'ML_RADAR_V14_SITE_REQ',id,payload},'*');setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(new Error('Conector ML Radar não detectado. Use esta página no onovoseller.com.br ou localhost com a extensão instalada.'));}},3500);});}
function rows(){return Object.values(state.records||{}).sort((a,b)=>a.keyword.localeCompare(b.keyword,'pt-BR'));}
function hist(r){return (r.history||[]).filter(x=>x?.found&&Number.isFinite(x.position));}
function variation(r){const h=hist(r);return h.length<2?null:h[h.length-2].position-h[h.length-1].position;}
function gap10(x){return x?.found?Math.max(0,x.position-10):null;}
async function init(){bind();const saved=localStorage.getItem('mlRadarSpeedV13');if(saved&&$('#speedMode'))$('#speedMode').value=saved;await refresh();renderAll();setInterval(refresh,direct()?1200:900);}
function bind(){const ti=$('#target');if(ti){if(targetDraft)ti.value=targetDraft;ti.addEventListener('focus',()=>{targetEditing=true;});ti.addEventListener('input',()=>{targetEditing=true;targetDraft=ti.value;sessionStorage.setItem('mlRadarTargetDraft',targetDraft);});ti.addEventListener('blur',()=>{targetEditing=false;targetDraft=ti.value;sessionStorage.setItem('mlRadarTargetDraft',targetDraft);});}$('#resolve').onclick=resolveTarget;$('#clearTarget').onclick=clearTarget;$('#analyze').onclick=()=>start(false);$('#analyzeSaved').onclick=()=>start(true);$('#testPage').onclick=testRunner;$('#cancel').onclick=cancel;$('#csv').onclick=exportCsv;$('#clearHistory').onclick=clearHistory;$('#historySelect').onchange=drawHistory;$('#speedMode').onchange=()=>localStorage.setItem('mlRadarSpeedV13',$('#speedMode').value);$('#reloadFrame').onclick=()=>navigateEmbed($('#mlFrame')?.src||'https://lista.mercadolivre.com.br/',true);$('#toggleFrame').onclick=toggleFrameInteraction;}
async function refresh(){const r=await msg({type:'GET_CONTEXT'}).catch(()=>null);if(r?.ok){state=r.state||state;job=r.job||null;runner=r.runner||null;if(job?.status==='running')showScan(job);else hideScan();renderAll(false);}}
function navigateEmbed(url,force=false){const f=$('#mlFrame');if(!f||!url)return;try{const current=f.src||'';if(force){const u=new URL(url,location.href);u.searchParams.set('_mlr',Date.now());f.src=u.href;return;}if(current!==url)f.src=url;}catch{f.src=url;}}
function toggleFrameInteraction(){const lock=$('#frameLock'),btn=$('#toggleFrame');const unlock=!lock.classList.contains('unlocked');lock.classList.toggle('unlocked',unlock);btn.textContent=unlock?'Bloquear':'Interagir';}
function updateRunner(){const dot=$('#runnerDot'),ready=!!runner?.frameId;if(ready){dot.className='dot '+(job?.status==='running'?'busy':'ok');$('#runnerStatus').textContent=job?.status==='running'?`Lendo “${job.keyword||''}”`:'Mercado Livre carregado dentro do painel.';}else{dot.className='dot';$('#runnerStatus').textContent='Carregando Mercado Livre dentro do painel...';}$('#livePage').textContent=job?.status==='running'?`Pág. ${job.page||1}`:'—';$('#runnerLiveTitle').textContent=job?.status==='running'?`Lendo: ${job.keyword||''}`:(ready?'Mercado Livre embutido pronto':'Aguardando Mercado Livre');$('#runnerLiveText').textContent=job?.status==='running'?`${(job.checked||0).toLocaleString('pt-BR')} anúncios já verificados.`:'Sem popup: a página real está no quadro à esquerda.';}
function handlePush(m){if(!m)return;if(m.type==='EMBED_NAVIGATE'||m.type==='MLRADAR_HOST_NAVIGATE'){navigateEmbed(m.url);return;}if(m.type==='SCAN_PROGRESS'&&m.job){job=m.job;if(job.status==='running')showScan(job);else hideScan();return;}if(m.type==='SCAN_COMPLETE'){state=m.state||state;job=m.job||job;hideScan();renderAll();return;}if(m.type==='STATE_UPDATED'&&m.state){state=m.state;renderAll();return;}if(m.type==='RUNNER_UPDATED'){runner=m.runner||null;updateRunner();}}
async function resolveTarget(){const raw=clean($('#target').value),info=$('#targetInfo');if(!raw){info.className='status err';info.textContent='Informe o MLB ou link.';return null;}info.className='status';info.textContent='Identificando...';const r=await msg({type:'RESOLVE_TARGET',value:raw}).catch(e=>({ok:false,error:String(e.message||e)}));if(!r?.ok){info.className='status err';info.textContent=r?.error||'Não consegui identificar.';return null;}state.target={mlb:r.mlb,title:r.title||'',familyName:r.familyName||'',permalink:r.permalink||'',sellerId:r.sellerId??null,sellerName:r.sellerName||'',userProductId:r.userProductId||'',catalogProductId:r.catalogProductId||'',relatedIds:r.relatedIds||[]};targetDraft='';targetEditing=false;sessionStorage.removeItem('mlRadarTargetDraft');const sv=await msg({type:'SET_TARGET',target:state.target}).catch(()=>null);if(sv?.state)state=sv.state;renderTarget();return state.target;}
async function clearTarget(){targetDraft='';targetEditing=false;sessionStorage.removeItem('mlRadarTargetDraft');const r=await msg({type:'SET_TARGET',target:null}).catch(()=>null);state=r?.state||{...state,target:null};if($('#target'))$('#target').value='';renderTarget();}
async function start(saved){if(job?.status==='running')return;if(!state.target?.mlb){const t=await resolveTarget();if(!t)return;}let words=saved?rows().map(x=>x.keyword):$('#keywordsInput').value.split(/[\n,;]+/).map(clean).filter(Boolean);words=[...new Set(words)];if(!words.length){alert('Digite pelo menos uma palavra-chave.');return;}const speedMode=$('#speedMode').value||'fast';const r=await msg({type:'START_SCAN',target:state.target,keywords:words,speedMode}).catch(e=>({ok:false,error:String(e.message||e)}));if(!r?.ok){alert(r?.error||'Não foi possível iniciar.');return;}job=r.job;runner=r.runner||runner;showScan(job);updateRunner();}
async function cancel(){await msg({type:'CANCEL_SCAN'}).catch(()=>{});job={...(job||{}),status:'cancelled'};hideScan();}
async function testRunner(){const el=$('#readStatus');el.textContent='Lendo...';const r=await msg({type:'TEST_RUNNER'}).catch(e=>({ok:false,error:String(e.message||e)}));if(!r?.ok){el.textContent=r?.error||'Falha.';return;}const p=r.parsed||{};el.textContent=`${p.itemsCount||0} anúncios lidos • Seguinte ${p.nextExists?'OK':'não visível'}${p.matchIndex>=0?' • seu anúncio está nesta página':''}`;}
function showScan(j){job=j;$('#scanCard').classList.remove('hidden');updateScan(j);updateRunner();}
function hideScan(){if($('#scanCard'))$('#scanCard').classList.add('hidden');updateRunner();}
function updateScan(j){$('#scanText').textContent=j.progressText||'Analisando...';$('#scanKeyword').textContent=j.keyword||'—';$('#scanPage').textContent=j.page||'—';$('#scanChecked').textContent=(j.checked||0).toLocaleString('pt-BR');$('#scanMode').textContent=(j.speedMode||'fast').toUpperCase();const base=(j.keywordIndex||0)/Math.max(1,j.keywords?.length||1)*100;$('#bar').style.width=`${Math.max(5,Math.min(97,base+Math.min(18,(j.page||1)*1.5)))}%`;}
function renderAll(redraw=true){renderTarget();renderStats();renderTable();renderFocus();renderHistorySelect();if(redraw){drawCompare();drawHistory();}updateRunner();}
function renderTarget(){const info=$('#targetInfo'),ti=$('#target');if(!state.target?.mlb){if(ti&&!targetEditing&&!targetDraft)ti.value='';info.className='status';info.textContent='Defina o anúncio que será procurado.';$('#productHeader').textContent='Defina seu anúncio';$('#productSub').textContent='Medição objetiva da posição por palavra-chave.';return;}if(ti&&!targetEditing&&!targetDraft)ti.value=state.target.mlb;info.className='status ok';info.innerHTML=`<strong>${esc(state.target.title||'Anúncio definido')}</strong><br>${esc(state.target.mlb)}`;$('#productHeader').textContent=state.target.title||state.target.mlb;$('#productSub').textContent=state.target.mlb;}
function renderStats(){const rs=rows(),f=rs.filter(r=>r.last?.found),ps=f.map(r=>r.last.position);$('#savedCount').textContent=`${rs.length} salvas`;if(ps.length){const b=Math.min(...ps),rr=f.find(r=>r.last.position===b);$('#best').textContent='#'+b;$('#bestKw').textContent=rr?.keyword||'';$('#avg').textContent='#'+Math.round(ps.reduce((a,b)=>a+b,0)/ps.length);}else{$('#best').textContent=$('#avg').textContent='—';$('#bestKw').textContent='sem dados';}$('#coverage').textContent=`${f.length} de ${rs.length} termos encontrados`;$('#top10').textContent=f.filter(r=>r.last.position<=10).length;$('#nearTop10').textContent=f.filter(r=>r.last.position>=11&&r.last.position<=30).length;$('#gaining').textContent=f.filter(r=>(variation(r)??0)>0).length;$('#falling').textContent=f.filter(r=>(variation(r)??0)<0).length;}
function renderTable(){const box=$('#metricsTable'),rs=rows();if(!rs.length){box.innerHTML='<div class="emptyrow">Nenhuma palavra monitorada.</div>';return;}box.innerHTML=`<div class="rank-row rank-head"><div>PALAVRA-CHAVE</div><div>POSIÇÃO</div><div>À FRENTE</div><div>PÁGINA</div><div>VARIAÇÃO</div><div>GAP TOP 10</div><div>PATROC. À FRENTE</div><div></div></div>`+rs.map(r=>{const x=r.last||{},v=variation(r),vt=v==null?'—':v>0?`<span class="up">▲ ${v}</span>`:v<0?`<span class="down">▼ ${Math.abs(v)}</span>`:'<span class="flat">0</span>';const status=!x.ok?`Erro: ${x.error||'leitura interrompida'}`:x.found?`${x.matchType||'ID exato'} • ${x.ts?new Date(x.ts).toLocaleString('pt-BR'):''}`:`Não encontrado • ${x.checked||0} verificados`;return`<div class="rank-row"><div class="kw"><b>${esc(r.keyword)}</b><br><span class="muted">${esc(status)}</span></div><div><b>${x.found?'#'+x.position:'—'}</b></div><div><b>${x.found?x.ahead:'—'}</b></div><div><b>${x.page||'—'}</b></div><div><b>${vt}</b></div><div><b>${x.found?gap10(x):'—'}</b></div><div><b>${x.found?(x.sponsoredAhead??0):'—'}</b></div><div><button class="delete" data-k="${esc(norm(r.keyword))}">Excluir</button></div></div>`}).join('');box.querySelectorAll('[data-k]').forEach(b=>b.onclick=async()=>{const r=await msg({type:'DELETE_KEYWORD',key:b.dataset.k});if(r?.state)state=r.state;renderAll();});}
function renderFocus(){const f=rows().filter(r=>r.last?.found);if(!f.length){$('#focusBox').textContent='Faça medições para identificar os termos mais próximos do Top 10 e as maiores quedas.';return;}const quick=f.filter(r=>r.last.position>10&&r.last.position<=30).sort((a,b)=>a.last.position-b.last.position);const drops=f.map(r=>({r,v:variation(r)})).filter(x=>x.v!=null&&x.v<0).sort((a,b)=>a.v-b.v);let parts=[];if(quick[0])parts.push(`Quick win: “${quick[0].keyword}” está em #${quick[0].last.position}; faltam ${gap10(quick[0].last)} posições para o Top 10.`);if(drops[0])parts.push(`Maior queda: “${drops[0].r.keyword}” caiu ${Math.abs(drops[0].v)} posições desde a medição anterior.`);if(!parts.length){const best=f.slice().sort((a,b)=>a.last.position-b.last.position)[0];parts.push(`Melhor termo atual: “${best.keyword}” em #${best.last.position}. Continue medindo antes e depois de alterações no anúncio.`);}$('#focusBox').textContent=parts.join('  ');}
function renderHistorySelect(){const s=$('#historySelect'),prev=s.value,rs=rows();s.innerHTML=rs.length?rs.map(r=>`<option value="${esc(norm(r.keyword))}">${esc(r.keyword)}</option>`).join(''):'<option value="">Sem palavras</option>';if(rs.some(r=>norm(r.keyword)===prev))s.value=prev;}
function setup(can){const rect=can.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(300,Math.floor(rect.width||480)),h=Math.max(170,Math.floor(rect.height||240));can.width=w*dpr;can.height=h*dpr;const c=can.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);return{c,w,h};}
function drawCompare(){const data=rows().map(r=>({keyword:r.keyword,...r.last})).filter(x=>x?.found),can=$('#chart'),empty=$('#chartEmpty'),{c,w,h}=setup(can);empty.style.display=data.length?'none':'grid';if(!data.length)return;const p={l:36,r:12,t:18,b:58},pw=w-p.l-p.r,ph=h-p.t-p.b,max=Math.max(10,...data.map(x=>x.position));c.font='9px Arial';c.fillStyle='#7790b5';c.strokeStyle='#30425e';for(let i=0;i<=4;i++){const y=p.t+ph*i/4,rank=Math.round(1+(max-1)*i/4);c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke();c.textAlign='right';c.fillText(rank,p.l-5,y+3)}const step=pw/data.length;c.strokeStyle='#18d3e6';c.lineWidth=2;c.beginPath();data.forEach((r,i)=>{const x=p.l+step*(i+.5),y=p.t+(r.position-1)/Math.max(1,max-1)*ph;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();data.forEach((r,i)=>{const x=p.l+step*(i+.5),y=p.t+(r.position-1)/Math.max(1,max-1)*ph;c.fillStyle='#ffe600';c.beginPath();c.arc(x,y,3.8,0,Math.PI*2);c.fill();c.fillStyle='#edf5ff';c.textAlign='center';c.font='bold 9px Arial';c.fillText('#'+r.position,x,y-8);c.save();c.translate(x,h-p.b+13);c.rotate(-.55);c.textAlign='right';c.font='8px Arial';c.fillStyle='#8299bb';c.fillText(r.keyword.length>18?r.keyword.slice(0,17)+'…':r.keyword,0,0);c.restore()});}
function drawHistory(){const s=$('#historySelect'),r=state.records?.[s.value],pts=hist(r||{}),can=$('#historyChart'),empty=$('#historyEmpty'),{c,w,h}=setup(can);empty.style.display=pts.length>=2?'none':'grid';if(pts.length<2)return;const p={l:36,r:12,t:18,b:26},pw=w-p.l-p.r,ph=h-p.t-p.b,max=Math.max(10,...pts.map(x=>x.position));c.font='9px Arial';c.fillStyle='#7790b5';c.strokeStyle='#30425e';for(let i=0;i<=4;i++){const y=p.t+ph*i/4,rank=Math.round(1+(max-1)*i/4);c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke();c.textAlign='right';c.fillText(rank,p.l-5,y+3)}const step=pw/Math.max(1,pts.length-1);c.strokeStyle='#a970ff';c.lineWidth=2;c.beginPath();pts.forEach((x,i)=>{const xx=p.l+step*i,yy=p.t+(x.position-1)/Math.max(1,max-1)*ph;i?c.lineTo(xx,yy):c.moveTo(xx,yy)});c.stroke();pts.forEach((x,i)=>{const xx=p.l+step*i,yy=p.t+(x.position-1)/Math.max(1,max-1)*ph;c.fillStyle='#ffe600';c.beginPath();c.arc(xx,yy,3.5,0,Math.PI*2);c.fill();});}
async function clearHistory(){if(!confirm('Apagar todas as palavras e históricos?'))return;const r=await msg({type:'CLEAR_HISTORY'});if(r?.state)state=r.state;renderAll();}
function exportCsv(){const out=[['Palavra-chave','Posição','À frente','Página','Variação','Gap Top 10','Patrocinados à frente','Atualizado']];for(const r of rows()){const x=r.last||{};out.push([r.keyword,x.position??'',x.ahead??'',x.page??'',variation(r)??'',x.found?gap10(x):'',x.sponsoredAhead??'',x.ts?new Date(x.ts).toISOString():'']);}const csv='\ufeff'+out.map(a=>a.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='ml-radar-v14.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
if(direct()){chrome.runtime.onMessage.addListener(m=>{handlePush(m);});}
window.addEventListener('resize',()=>{drawCompare();drawHistory();});init();